name: testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  version-check:
    # We want to run on external PRs, but not on our own internal
    # PRs as they'll be run by the push to the branch.
    #
    # The main trick is described here:
    # https://github.com/Dart-Code/Dart-Code/pull/2375
    if: github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-20.04
    steps:
      - name: Check module version
        # We need this step to run only on push with tag.
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'avro_schema'

  linux:
    # We want to run on external PRs, but not on our own internal
    # PRs as they'll be run by the push to the branch.
    #
    # The main trick is described here:
    # https://github.com/Dart-Code/Dart-Code/pull/2375
    if: github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tarantool:
          - '1.10'
          - '2.8'
          - '2.9'

    steps:
      - name: Clone the module
        uses: actions/checkout@v2

      - name: Setup tarantool ${{ matrix.tarantool }}
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - run: cmake . && make
      - run: make check
